"""add_assignment_status_real

Revision ID: 7ba388eecd31
Revises: f18c6691c7ab
Create Date: 2026-01-31 03:07:54.401380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba388eecd31'
down_revision: Union[str, Sequence[str], None] = 'f18c6691c7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        # Add column with default value for existing rows
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False, server_default='confirmed'))
        batch_op.add_column(sa.Column('decline_reason', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('decline_reason')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
