"""initial

Revision ID: f18c6691c7ab
Revises: 
Create Date: 2026-01-30 09:55:25.465648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import api.models


# revision identifiers, used by Alembic.
revision: str = 'f18c6691c7ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_action_timestamp', ['action', 'timestamp'], unique=False)
        batch_op.create_index('idx_audit_org_timestamp', ['organization_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_audit_user_timestamp', ['user_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('config', api.models.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('data_retention_until', sa.DateTime(), nullable=True),
    sa.Column('deletion_scheduled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constraints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('predicate', sa.String(), nullable=False),
    sa.Column('params', api.models.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('constraints', schema=None) as batch_op:
        batch_op.create_index('idx_constraints_key', ['key'], unique=False)
        batch_op.create_index('idx_constraints_org_id', ['org_id'], unique=False)

    op.create_table('holidays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('is_long_weekend', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_index('idx_holidays_date', ['date'], unique=False)
        batch_op.create_index('idx_holidays_org_id', ['org_id'], unique=False)

    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('stripe_payment_method_id', sa.String(length=255), nullable=False),
    sa.Column('card_brand', sa.String(length=20), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('exp_month', sa.Integer(), nullable=True),
    sa.Column('exp_year', sa.Integer(), nullable=True),
    sa.Column('billing_address', api.models.JSONType(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_method_id')
    )
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.create_index('idx_payment_methods_org_id', ['org_id'], unique=False)
        batch_op.create_index('idx_payment_methods_stripe_pm', ['stripe_payment_method_id'], unique=False)

    op.create_table('people',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('roles', api.models.JSONType(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('invited_by', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('calendar_token', sa.String(), nullable=True),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('extra_data', api.models.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['people.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_token')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index('idx_people_calendar_token', ['calendar_token'], unique=False)
        batch_op.create_index('idx_people_email', ['email'], unique=False)
        batch_op.create_index('idx_people_org_id', ['org_id'], unique=False)
        batch_op.create_index('idx_people_status', ['status'], unique=False)

    op.create_table('resources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('extra_data', api.models.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index('idx_resources_org_id', ['org_id'], unique=False)

    op.create_table('sms_usage',
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('month_year', sa.String(length=7), nullable=False),
    sa.Column('assignment_count', sa.Integer(), nullable=False),
    sa.Column('reminder_count', sa.Integer(), nullable=False),
    sa.Column('broadcast_count', sa.Integer(), nullable=False),
    sa.Column('system_count', sa.Integer(), nullable=False),
    sa.Column('total_cost_cents', sa.Integer(), nullable=False),
    sa.Column('budget_limit_cents', sa.Integer(), nullable=False),
    sa.Column('alert_threshold_percent', sa.Integer(), nullable=False),
    sa.Column('alert_sent_at_80', sa.Boolean(), nullable=False),
    sa.Column('alert_sent_at_100', sa.Boolean(), nullable=False),
    sa.Column('auto_pause_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'month_year')
    )
    with op.batch_alter_table('sms_usage', schema=None) as batch_op:
        batch_op.create_index('idx_sms_usage_month', ['month_year'], unique=False)

    op.create_table('solutions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('solve_ms', sa.Float(), nullable=True),
    sa.Column('hard_violations', sa.Integer(), nullable=False),
    sa.Column('soft_score', sa.Float(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('metrics', api.models.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solutions', schema=None) as batch_op:
        batch_op.create_index('idx_solutions_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_solutions_org_id', ['org_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('plan_tier', sa.String(length=20), nullable=False),
    sa.Column('billing_cycle', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trial_end_date', sa.DateTime(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('pending_downgrade', api.models.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('idx_subscriptions_org_id', ['org_id'], unique=False)
        batch_op.create_index('idx_subscriptions_org_status', ['org_id', 'status'], unique=False)
        batch_op.create_index('idx_subscriptions_status', ['status'], unique=False)
        batch_op.create_index('idx_subscriptions_stripe_customer', ['stripe_customer_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('extra_data', api.models.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index('idx_teams_org_id', ['org_id'], unique=False)

    op.create_table('usage_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('plan_limit', sa.Integer(), nullable=True),
    sa.Column('percentage_used', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_metrics', schema=None) as batch_op:
        batch_op.create_index('idx_usage_metrics_org_metric', ['org_id', 'metric_type'], unique=False)

    op.create_table('availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('rrule', sa.String(), nullable=True),
    sa.Column('extra_data', api.models.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.create_index('idx_availability_person_id', ['person_id'], unique=False)

    op.create_table('billing_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('stripe_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('invoice_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_metadata', api.models.JSONType(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_invoice_id')
    )
    with op.batch_alter_table('billing_history', schema=None) as batch_op:
        batch_op.create_index('idx_billing_history_org_timestamp', ['org_id', 'event_timestamp'], unique=False)
        batch_op.create_index('idx_billing_history_stripe_invoice', ['stripe_invoice_id'], unique=False)

    op.create_table('email_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('enabled_types', api.models.JSONType(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('digest_hour', sa.Integer(), nullable=False),
    sa.Column('unsubscribe_token', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id'),
    sa.UniqueConstraint('unsubscribe_token')
    )
    with op.batch_alter_table('email_preferences', schema=None) as batch_op:
        batch_op.create_index('idx_email_preferences_org_id', ['org_id'], unique=False)
        batch_op.create_index('idx_email_preferences_person_id', ['person_id'], unique=False)

    op.create_table('invitations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('roles', api.models.JSONType(), nullable=False),
    sa.Column('invited_by', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['people.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index('idx_invitations_email', ['email'], unique=False)
        batch_op.create_index('idx_invitations_org_id', ['org_id'], unique=False)
        batch_op.create_index('idx_invitations_status', ['status'], unique=False)
        batch_op.create_index('idx_invitations_token', ['token'], unique=False)

    op.create_table('onboarding_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('wizard_step_completed', sa.Integer(), nullable=True),
    sa.Column('wizard_data', api.models.JSONType(), nullable=True),
    sa.Column('checklist_state', api.models.JSONType(), nullable=True),
    sa.Column('tutorials_completed', api.models.JSONType(), nullable=True),
    sa.Column('features_unlocked', api.models.JSONType(), nullable=True),
    sa.Column('videos_watched', api.models.JSONType(), nullable=True),
    sa.Column('onboarding_skipped', sa.Boolean(), nullable=True),
    sa.Column('checklist_dismissed', sa.Boolean(), nullable=True),
    sa.Column('tutorials_dismissed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    with op.batch_alter_table('onboarding_progress', schema=None) as batch_op:
        batch_op.create_index('idx_onboarding_progress_org_id', ['org_id'], unique=False)
        batch_op.create_index('idx_onboarding_progress_person_id', ['person_id'], unique=False)

    op.create_table('recurring_series',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('role_requirements', api.models.JSONType(), nullable=True),
    sa.Column('pattern_type', sa.String(), nullable=False),
    sa.Column('frequency_interval', sa.Integer(), nullable=True),
    sa.Column('selected_days', api.models.JSONType(), nullable=True),
    sa.Column('weekday_position', sa.String(), nullable=True),
    sa.Column('weekday_name', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_condition_type', sa.String(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['people.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_series', schema=None) as batch_op:
        batch_op.create_index('idx_recurring_series_active', ['active'], unique=False)
        batch_op.create_index('idx_recurring_series_created_by', ['created_by'], unique=False)
        batch_op.create_index('idx_recurring_series_org_id', ['org_id'], unique=False)
        batch_op.create_index('idx_recurring_series_start_date', ['start_date'], unique=False)

    op.create_table('sms_preferences',
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('notification_types', api.models.JSONType(), nullable=False),
    sa.Column('opt_in_date', sa.DateTime(), nullable=True),
    sa.Column('opt_out_date', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id')
    )
    with op.batch_alter_table('sms_preferences', schema=None) as batch_op:
        batch_op.create_index('idx_sms_preferences_verified', ['verified', 'opt_out_date'], unique=False)

    op.create_table('sms_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('translations', api.models.JSONType(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_templates', schema=None) as batch_op:
        batch_op.create_index('idx_sms_templates_org_type', ['organization_id', 'message_type'], unique=False)
        batch_op.create_index('idx_sms_templates_system', ['is_system'], unique=False)

    op.create_table('sms_verification_codes',
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('verification_code', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id')
    )
    with op.batch_alter_table('sms_verification_codes', schema=None) as batch_op:
        batch_op.create_index('idx_sms_verification_expires', ['expires_at'], unique=False)

    op.create_table('subscription_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('previous_plan', sa.String(length=20), nullable=True),
    sa.Column('new_plan', sa.String(length=20), nullable=False),
    sa.Column('admin_id', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra_metadata', api.models.JSONType(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription_events', schema=None) as batch_op:
        batch_op.create_index('idx_subscription_events_org_timestamp', ['org_id', 'event_timestamp'], unique=False)
        batch_op.create_index('idx_subscription_events_type', ['event_type'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index('idx_team_members_person_id', ['person_id'], unique=False)
        batch_op.create_index('idx_team_members_team_id', ['team_id'], unique=False)

    op.create_table('availability_exceptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('availability_id', sa.Integer(), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['availability_id'], ['availability.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability_exceptions', schema=None) as batch_op:
        batch_op.create_index('idx_availability_exceptions_availability_id', ['availability_id'], unique=False)
        batch_op.create_index('idx_availability_exceptions_date', ['exception_date'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('extra_data', api.models.JSONType(), nullable=True),
    sa.Column('series_id', sa.String(), nullable=True),
    sa.Column('occurrence_sequence', sa.Integer(), nullable=True),
    sa.Column('is_exception', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['recurring_series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_events_org_id', ['org_id'], unique=False)
        batch_op.create_index('idx_events_series_id', ['series_id'], unique=False)
        batch_op.create_index('idx_events_start_time', ['start_time'], unique=False)

    op.create_table('vacation_periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('availability_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['availability_id'], ['availability.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vacation_periods', schema=None) as batch_op:
        batch_op.create_index('idx_vacation_periods_availability_id', ['availability_id'], unique=False)
        batch_op.create_index('idx_vacation_periods_dates', ['start_date', 'end_date'], unique=False)

    op.create_table('assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index('idx_assignments_event_id', ['event_id'], unique=False)
        batch_op.create_index('idx_assignments_person_id', ['person_id'], unique=False)
        batch_op.create_index('idx_assignments_solution_id', ['solution_id'], unique=False)

    op.create_table('event_teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_teams', schema=None) as batch_op:
        batch_op.create_index('idx_event_teams_event_id', ['event_id'], unique=False)
        batch_op.create_index('idx_event_teams_team_id', ['team_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('recipient_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('template_data', api.models.JSONType(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('sendgrid_message_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sendgrid_message_id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notifications_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_notifications_event_id', ['event_id'], unique=False)
        batch_op.create_index('idx_notifications_org_id', ['org_id'], unique=False)
        batch_op.create_index('idx_notifications_recipient_id', ['recipient_id'], unique=False)
        batch_op.create_index('idx_notifications_status', ['status'], unique=False)

    op.create_table('recurrence_exceptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('occurrence_id', sa.String(), nullable=False),
    sa.Column('series_id', sa.String(), nullable=False),
    sa.Column('exception_type', sa.String(), nullable=False),
    sa.Column('original_title', sa.String(), nullable=True),
    sa.Column('original_start_time', sa.DateTime(), nullable=True),
    sa.Column('original_end_time', sa.DateTime(), nullable=True),
    sa.Column('original_location', sa.String(), nullable=True),
    sa.Column('custom_title', sa.String(), nullable=True),
    sa.Column('custom_start_time', sa.DateTime(), nullable=True),
    sa.Column('custom_end_time', sa.DateTime(), nullable=True),
    sa.Column('custom_location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['occurrence_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['recurring_series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('occurrence_id')
    )
    with op.batch_alter_table('recurrence_exceptions', schema=None) as batch_op:
        batch_op.create_index('idx_recurrence_exceptions_occurrence_id', ['occurrence_id'], unique=False)
        batch_op.create_index('idx_recurrence_exceptions_series_id', ['series_id'], unique=False)

    op.create_table('sms_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('recipient_id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('twilio_message_sid', sa.String(length=34), nullable=True),
    sa.Column('cost_cents', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['sms_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twilio_message_sid')
    )
    with op.batch_alter_table('sms_messages', schema=None) as batch_op:
        batch_op.create_index('idx_sms_messages_org_created', ['organization_id', 'created_at'], unique=False)
        batch_op.create_index('idx_sms_messages_recipient_created', ['recipient_id', 'created_at'], unique=False)
        batch_op.create_index('idx_sms_messages_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('idx_sms_messages_twilio_sid', ['twilio_message_sid'], unique=False)
        batch_op.create_index('idx_sms_messages_type_created', ['message_type', 'created_at'], unique=False)

    op.create_table('delivery_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('sendgrid_message_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('raw_event', api.models.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_logs', schema=None) as batch_op:
        batch_op.create_index('idx_delivery_logs_notification_id', ['notification_id'], unique=False)
        batch_op.create_index('idx_delivery_logs_sendgrid_message_id', ['sendgrid_message_id'], unique=False)
        batch_op.create_index('idx_delivery_logs_timestamp', ['timestamp'], unique=False)

    op.create_table('sms_replies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('reply_type', sa.String(length=20), nullable=False),
    sa.Column('original_message_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('action_taken', sa.String(length=50), nullable=False),
    sa.Column('twilio_message_sid', sa.String(length=34), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_message_id'], ['sms_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twilio_message_sid')
    )
    with op.batch_alter_table('sms_replies', schema=None) as batch_op:
        batch_op.create_index('idx_sms_replies_person_created', ['person_id', 'created_at'], unique=False)
        batch_op.create_index('idx_sms_replies_twilio_sid', ['twilio_message_sid'], unique=False)
        batch_op.create_index('idx_sms_replies_type_created', ['reply_type', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_replies', schema=None) as batch_op:
        batch_op.drop_index('idx_sms_replies_type_created')
        batch_op.drop_index('idx_sms_replies_twilio_sid')
        batch_op.drop_index('idx_sms_replies_person_created')

    op.drop_table('sms_replies')
    with op.batch_alter_table('delivery_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_delivery_logs_timestamp')
        batch_op.drop_index('idx_delivery_logs_sendgrid_message_id')
        batch_op.drop_index('idx_delivery_logs_notification_id')

    op.drop_table('delivery_logs')
    with op.batch_alter_table('sms_messages', schema=None) as batch_op:
        batch_op.drop_index('idx_sms_messages_type_created')
        batch_op.drop_index('idx_sms_messages_twilio_sid')
        batch_op.drop_index('idx_sms_messages_status_created')
        batch_op.drop_index('idx_sms_messages_recipient_created')
        batch_op.drop_index('idx_sms_messages_org_created')

    op.drop_table('sms_messages')
    with op.batch_alter_table('recurrence_exceptions', schema=None) as batch_op:
        batch_op.drop_index('idx_recurrence_exceptions_series_id')
        batch_op.drop_index('idx_recurrence_exceptions_occurrence_id')

    op.drop_table('recurrence_exceptions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_notifications_status')
        batch_op.drop_index('idx_notifications_recipient_id')
        batch_op.drop_index('idx_notifications_org_id')
        batch_op.drop_index('idx_notifications_event_id')
        batch_op.drop_index('idx_notifications_created_at')

    op.drop_table('notifications')
    with op.batch_alter_table('event_teams', schema=None) as batch_op:
        batch_op.drop_index('idx_event_teams_team_id')
        batch_op.drop_index('idx_event_teams_event_id')

    op.drop_table('event_teams')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index('idx_assignments_solution_id')
        batch_op.drop_index('idx_assignments_person_id')
        batch_op.drop_index('idx_assignments_event_id')

    op.drop_table('assignments')
    with op.batch_alter_table('vacation_periods', schema=None) as batch_op:
        batch_op.drop_index('idx_vacation_periods_dates')
        batch_op.drop_index('idx_vacation_periods_availability_id')

    op.drop_table('vacation_periods')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('idx_events_start_time')
        batch_op.drop_index('idx_events_series_id')
        batch_op.drop_index('idx_events_org_id')

    op.drop_table('events')
    with op.batch_alter_table('availability_exceptions', schema=None) as batch_op:
        batch_op.drop_index('idx_availability_exceptions_date')
        batch_op.drop_index('idx_availability_exceptions_availability_id')

    op.drop_table('availability_exceptions')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index('idx_team_members_team_id')
        batch_op.drop_index('idx_team_members_person_id')

    op.drop_table('team_members')
    with op.batch_alter_table('subscription_events', schema=None) as batch_op:
        batch_op.drop_index('idx_subscription_events_type')
        batch_op.drop_index('idx_subscription_events_org_timestamp')

    op.drop_table('subscription_events')
    with op.batch_alter_table('sms_verification_codes', schema=None) as batch_op:
        batch_op.drop_index('idx_sms_verification_expires')

    op.drop_table('sms_verification_codes')
    with op.batch_alter_table('sms_templates', schema=None) as batch_op:
        batch_op.drop_index('idx_sms_templates_system')
        batch_op.drop_index('idx_sms_templates_org_type')

    op.drop_table('sms_templates')
    with op.batch_alter_table('sms_preferences', schema=None) as batch_op:
        batch_op.drop_index('idx_sms_preferences_verified')

    op.drop_table('sms_preferences')
    with op.batch_alter_table('recurring_series', schema=None) as batch_op:
        batch_op.drop_index('idx_recurring_series_start_date')
        batch_op.drop_index('idx_recurring_series_org_id')
        batch_op.drop_index('idx_recurring_series_created_by')
        batch_op.drop_index('idx_recurring_series_active')

    op.drop_table('recurring_series')
    with op.batch_alter_table('onboarding_progress', schema=None) as batch_op:
        batch_op.drop_index('idx_onboarding_progress_person_id')
        batch_op.drop_index('idx_onboarding_progress_org_id')

    op.drop_table('onboarding_progress')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index('idx_invitations_token')
        batch_op.drop_index('idx_invitations_status')
        batch_op.drop_index('idx_invitations_org_id')
        batch_op.drop_index('idx_invitations_email')

    op.drop_table('invitations')
    with op.batch_alter_table('email_preferences', schema=None) as batch_op:
        batch_op.drop_index('idx_email_preferences_person_id')
        batch_op.drop_index('idx_email_preferences_org_id')

    op.drop_table('email_preferences')
    with op.batch_alter_table('billing_history', schema=None) as batch_op:
        batch_op.drop_index('idx_billing_history_stripe_invoice')
        batch_op.drop_index('idx_billing_history_org_timestamp')

    op.drop_table('billing_history')
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_index('idx_availability_person_id')

    op.drop_table('availability')
    with op.batch_alter_table('usage_metrics', schema=None) as batch_op:
        batch_op.drop_index('idx_usage_metrics_org_metric')

    op.drop_table('usage_metrics')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index('idx_teams_org_id')

    op.drop_table('teams')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index('idx_subscriptions_stripe_customer')
        batch_op.drop_index('idx_subscriptions_status')
        batch_op.drop_index('idx_subscriptions_org_status')
        batch_op.drop_index('idx_subscriptions_org_id')

    op.drop_table('subscriptions')
    with op.batch_alter_table('solutions', schema=None) as batch_op:
        batch_op.drop_index('idx_solutions_org_id')
        batch_op.drop_index('idx_solutions_created_at')

    op.drop_table('solutions')
    with op.batch_alter_table('sms_usage', schema=None) as batch_op:
        batch_op.drop_index('idx_sms_usage_month')

    op.drop_table('sms_usage')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index('idx_resources_org_id')

    op.drop_table('resources')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index('idx_people_status')
        batch_op.drop_index('idx_people_org_id')
        batch_op.drop_index('idx_people_email')
        batch_op.drop_index('idx_people_calendar_token')

    op.drop_table('people')
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index('idx_payment_methods_stripe_pm')
        batch_op.drop_index('idx_payment_methods_org_id')

    op.drop_table('payment_methods')
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index('idx_holidays_org_id')
        batch_op.drop_index('idx_holidays_date')

    op.drop_table('holidays')
    with op.batch_alter_table('constraints', schema=None) as batch_op:
        batch_op.drop_index('idx_constraints_org_id')
        batch_op.drop_index('idx_constraints_key')

    op.drop_table('constraints')
    op.drop_table('organizations')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('idx_audit_user_timestamp')
        batch_op.drop_index('idx_audit_org_timestamp')
        batch_op.drop_index('idx_audit_action_timestamp')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
