"""Reviewed authentication policy for every mounted API operation.

The policy is deliberately keyed by FastAPI operation name. A unit test compares
this mapping with the live route table, so a new API route cannot ship without an
explicit public, token, member, or administrator classification.
"""

PUBLIC_OPERATIONS = {
    "api_info",
    "api_redirect",
    "check_email",
    "health_check",
    "login",
    "readiness_check",
    "signup",
}

PUBLIC_TOKEN_OPERATIONS = {
    "accept_invitation",
    "calendar_feed",
    "refresh",
    "request_password_reset",
    "reset_password",
    "verify_invitation",
}

PUBLIC_CALLBACK_OPERATIONS = {
    "twilio_delivery_status_webhook",
    "twilio_incoming_sms_webhook",
}

MEMBER_OPERATIONS = {
    "accept_assignment",
    "add_exception",
    "add_timeoff",
    "change_password",
    "clear_rrule",
    "create_availability",
    "decline_assignment",
    "delete_exception",
    "delete_timeoff",
    "export_personal_schedule",
    "get_current_person",
    "get_constraint",
    "get_event",
    "get_holiday",
    "get_my_email_preferences",
    "get_notification",
    "get_organization",
    "get_person",
    "get_recurring_series",
    "get_resource",
    "get_rrule",
    "get_series_occurrences",
    "get_subscription_url",
    "get_team",
    "get_timeoff",
    "get_unread_count",
    "list_constraints",
    "list_events",
    "list_exceptions",
    "list_holidays",
    "list_my_assignments",
    "list_notifications",
    "list_organizations",
    "list_people",
    "list_recurring_series",
    "list_resources",
    "list_teams",
    "mark_notification_read",
    "preview_occurrences",
    "request_swap",
    "reset_calendar_token",
    "send_verification_code",
    "set_rrule",
    "update_current_person",
    "update_my_email_preferences",
    "update_person",
    "update_sms_preferences",
    "update_timeoff",
    "verify_code",
    "verify_phone_number",
}

ADMIN_OPERATIONS = {
    "add_payment_method",
    "add_team_members",
    "admin_reset_calendar_token",
    "bulk_import_holidays",
    "bulk_import_people",
    "cancel_downgrade",
    "cancel_invitation",
    "cancel_organization",
    "cancel_subscription",
    "check_conflicts",
    "compare_solutions",
    "create_billing_portal_session",
    "create_constraint",
    "create_event",
    "create_holiday",
    "create_invitation",
    "create_manual_solution",
    "create_person",
    "create_recurring_series",
    "create_resource",
    "create_team",
    "delete_constraint",
    "delete_event",
    "delete_holiday",
    "delete_organization",
    "delete_person",
    "delete_recurring_series",
    "delete_resource",
    "delete_solution",
    "delete_team",
    "download_invoice_pdf",
    "downgrade_subscription",
    "export_organization_events",
    "export_solution",
    "get_all_assignments",
    "get_available_people",
    "get_billing_history",
    "get_burnout_risk",
    "get_organization_notification_stats",
    "get_payment_methods",
    "get_schedule_health",
    "get_sms_usage_stats",
    "get_solution",
    "get_solution_assignments",
    "get_solution_stats",
    "get_subscription",
    "get_volunteer_stats",
    "handle_checkout_success",
    "list_audit_logs",
    "list_conflicts",
    "list_invitations",
    "list_solutions",
    "manage_assignment",
    "publish_solution",
    "reactivate_subscription",
    "remove_payment_method",
    "remove_team_members",
    "resend_invitation",
    "restore_organization",
    "rollback_solution",
    "send_assignment_notification_api",
    "send_broadcast_api",
    "send_event_reminder_api",
    "send_test_notification",
    "set_primary_payment_method",
    "solve_schedule",
    "start_trial",
    "stream_solution_assignments",
    "unpublish_solution",
    "update_constraint",
    "update_event",
    "update_holiday",
    "update_organization",
    "update_resource",
    "update_series_template",
    "update_team",
    "upgrade_subscription",
    "validate_event",
}

ROUTE_AUTH_POLICY = {
    **{name: "public" for name in PUBLIC_OPERATIONS},
    **{name: "public-token" for name in PUBLIC_TOKEN_OPERATIONS},
    **{name: "public-callback" for name in PUBLIC_CALLBACK_OPERATIONS},
    **{name: "member" for name in MEMBER_OPERATIONS},
    **{name: "admin" for name in ADMIN_OPERATIONS},
}
